apiVersion: apps/v1
kind: Deployment
metadata:
  name: faust-enrichposts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faust-enrichposts
  template:
    metadata:
      labels:
        app: faust-enrichposts
    spec:
      containers:
      - name: faust-enrichposts
        image: "faust-enrichposts:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER
          value: {{.Release.Name}}-kafka
        - name: MONGO_URI
          value: "mongodb://{{ .Values.mongodb.service.type }}:{{ .Values.mongodb.service.port }}/"
        - name: VK_POSTS_TOPIC
          value: "{{ .Values.topics.vkPulledPostsTopicName }}"
        - name: ENRICHED_TOPIC
          value: "{{ .Values.topics.enrichedVkPostsTopicName }}"
        ports:
        - containerPort: 6066 # Faust web port (optional)
        command: ["faust", "-A", "app", "worker", "-l", "info"]
