apiVersion: v1
kind: Pod
metadata:
  name: fetcher-admin
spec:
  containers:
  - name: fetcher-admin
    image: fetcher-admin:latest
    imagePullPolicy: Never
    env:
    - name: KAFKA_ADMIN_COMMANDS_TOPIC_NAME
      value: {{ .Values.topics.kafkaAdminCommandsTopicName | default "kafka_admin_commands" }}
    - name: FETCHER_ADMIN_COMMANDS_TOPIC_NAME
      value: {{ .Values.topics.fetcherAdminCommandsTopicName | default "fetcher_admin_commands" }}
    - name: VK_FETCHERS_COMMANDS_TOPIC_NAME
      value: {{ .Values.topics.vkFetchersCommandsTopicName | default "vk_fetcher_commands" }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{.Release.Name}}-kafka