apiVersion: v1
kind: Pod
metadata:
  name: vk-fetcher
spec:
  containers:
  - name: vk-fetcher
    image: vk-fetcher:latest
    imagePullPolicy: Never
    env:
    - name: VK_FETCHERS_COMMANDS_TOPIC_NAME
      value: {{ .Values.topics.vkFetchersCommandsTopicName | default "vk_fetcher_commands" }}
    - name: VK_PULLED_POSTS_TOPIC_NAME
      value: {{ .Values.topics.vkPulledPostsTopicName | default "vk_posts" }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{.Release.Name}}-kafka
