apiVersion: v1
kind: Pod
metadata:
  name: bot-writer
spec:
  containers:
  - name: bot-writer
    image: bot-writer:latest
    imagePullPolicy: Never
    env:
    - name: TELEGRAM_BOT_TOKEN
      value: {{ .Values.telegramBotToken}}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{.Release.Name}}-kafka