mongodb:
  enabled: true
  architecture: standalone
  replicaCount: 1
  auth:
    enabled: false
    rootPassword: "rootpassword"
    usernames: []
    passwords: []
    databases: []
  persistence:
    enabled: true
    size: 8Gi
  service:
    type: ClusterIP
    port: 27017

kafka:
  enabled: true
  replicaCount: 1
  kraft:
    enabled: true
    controllerQuorumVoters: "1@kafka-0.kafka-headless.default.svc.cluster.local:9093"
    clusterId: "Mk3OEYBSD34fcwNTJENDM2Qk"
  listeners:
    client:
      protocol: PLAINTEXT
      port: 9092
    controller:
      protocol: PLAINTEXT
      port: 9093
  service:
    name: kafka
    type: ClusterIP
    ports:
      client: 9092
      controller: 9093
  persistence:
    enabled: true
    size: 8Gi
  autoCreateTopicsEnable: false
  logDirs:
    - /bitnami/kafka/data
  extraEnvVars:
    - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
      value: "0"
    - name: KAFKA_LOG_RETENTION_HOURS
      value: "168"

topics:
  fetcherAdminCommandsTopicName: "fetcher_admin_commands"
  kafkaAdminCommandsTopicName: "kafka_admin_commands"
  vkFetchersCommandsTopicName: "vk_fetcher_commands"
  validatorTopicName: "validator_commands"
  writerTopicName: "writer_commands"
  vkPulledPostsTopicName: "vk_posts"

telegramBotToken: "6244825355:AAEWNuVCRWHlk4QxSLB9-eeIyytoXnOSfhI"
