# target_groups_ids: set = {"public192867633", 
#                            "lovelycosplay", 
#                            "miptdndleague", 
#                            "stfpmi", 
#                            "anifox", 
#                            "fpmi_edu", 
#                            "reddit", 
#                            "twinsrpg", 
#                            "marsbgame", 
#                            "best_rpg_games", 
#                            "starcraft_memes", 
#                            "dit2225", 
#                            "lore_dnd", 
#                            "fpmi_students", 
#                            "kleientertainment", 
#                            "anime", 
#                            "knigiprint", 
#                            "cpp_lib", 
#                            "resf"}

# VK_PULLED_POSTS_TOPIC_NAME: str = "vk_posts"
